getBilinearInterp – C81 Interface
getBilinearInterp Function
11 statements
Source File
public function getBilinearInterp(x, y, xvec, yvec, f11, f12, f21, f22)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
real, intent(in) :: y
real, intent(in), dimension(2) :: xvec
real, intent(in), dimension(2) :: yvec
real, intent(in) :: f11
real, intent(in) :: f12
real, intent(in) :: f21
real, intent(in) :: f22
Return Value real
Called by
Contents
Source Code
getBilinearInterp
Source Code
  function getBilinearInterp(x,y,xvec,yvec,f11,f12,f21,f22)
    real, intent(in) :: x, y
    real, intent(in), dimension(2) :: xvec, yvec
    real, intent(in) :: f11, f12, f21, f22
    real :: getBilinearInterp
    real, dimension(2,2) :: fMat
    fMat(1,:) = (/f11,f12/)
    fMat(2,:) = (/f21,f22/)
    getBilinearInterp = dot_product((/xvec(2)-x,x-xvec(1)/),matmul(fMat,(/yvec(2)-y,y-yvec(1)/)))
    getBilinearInterp = getBilinearInterp/(xvec(2)-xvec(1))/(yvec(2)-yvec(1))
  end function getBilinearInterp
Call graph
getcd calls getbilinearinterp
getcl calls getbilinearinterp
getcm calls getbilinearinterp