getInterval – C81 Interface
getInterval Function
25 statements
Source File
public function getInterval(A, x) result(indx)
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(:) :: A
real, intent(in) :: x
Return Value integer, dimension(2)
Called by
Contents
Source Code
getInterval
Source Code
  function getInterval(A,x) result(indx)
    real, intent(in), dimension(:) :: A
    real, intent(in) :: x
    integer, dimension(2) :: indx  ! Left and right indices
    integer :: n, i
    n = size(A,1)
    indx(1) = 1
    indx(2) = n
    ! Binary search algorithm
    do while ((indx(1) .ne. indx(2)) .and. (indx(2) .ne. (indx(1)+1)))
      i = floor((indx(1)+indx(2))*0.5)
      if (x < A(i)) then
        indx(2) = i
      elseif (x > A(i)) then
        indx(1) = i
      else
        indx(1) = i
        indx(2) = i
      endif
    enddo
    ! Check end cases
    if (abs(A(indx(1))-x) .le. epsilon(1.)) then
      indx(2) = indx(1)
    elseif (abs(A(indx(2))-x) .le. epsilon(1.)) then
      indx(1) = indx(2)
    endif
  end function getInterval
Call graph
getcd calls getinterval
demo1 calls getinterval
getcl calls getinterval
getcm calls getinterval